sudo: required
services:
  - docker

before_install:
  - docker build -t jonathansilverstein/frontend -f Dockerfile.dev .

scripts:
  docker run -e CI=true jonathansilverstein/frontend npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2 #Double check this
  app: frontend
  env: frontend-env #Double check this
  bucket_name: #S3 bucket generated when you create EBS application
  bucket_path: frontend #equal to the app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY